version: '3'
services:
  mate-desktop:
    security_opt:
    - seccomp:unconfined
    shm_size: "2gb"
    environment:
    - USER={{ USERNAME }}
    - PASSWORD={{ PASSWORD }}
    - LANG={{ LOCALE }}
    - TZ={{ TIMEZONE }}
    cap_add:
    - SYS_PTRACE
    image: ramirezfx/linuxmint-desktop:{{ VERSION }}
    restart: always
    stdin_open: true
    tty: true
    ports:
    - {{ NOMACHINE_PORT }}:4000/tcp
    - {{ NOMACHINE_UDP_PORT }}:4000/udp
