version: '3'
services:
  mate-desktop:
    security_opt:
    - seccomp:unconfined
    shm_size: "2gb"
    environment:
    - USER={{ USERNAME }}
    - PASSWORD={{ PASSWORD }}
    cap_add:
    - SYS_PTRACE
    image: ramirezfx/linuxmint-desktop:cinnamon-latest
    restart: always
    stdin_open: true
    tty: true
    ports:
    - 4005:4000/tcp
    - 2222:22/tcp
