version: '3'
services:
  mate-desktop:
    security_opt:
    - seccomp:unconfined
    shm_size: "2gb"
    environment:
    - USER={{ USERNAME }}
    - PASSWORD={{ PASSWORD }}
    - LANG={{ LOCALE }}
    - TZ={{ TIMEZONE }}
    cap_add:
    - SYS_PTRACE
    - net_admin
    image: ramirezfx/linuxmint-desktop:{{ VERSION }}
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /dev/net/tun:/dev/net/tun
      - {{DATADIR}}:/data
